/* Types auto-generated by vite-plugin-intric-icons, do not edit. */
declare module "@intric/icons/*" {
  import { SvelteComponent } from "svelte";
  import type { SvelteHTMLElements } from "svelte/elements";
  type IconProps = { size?: "sm" | "md" | "lg" };
  export class Icon extends SvelteComponent<IconProps & SvelteHTMLElements["svg"]> {}
}
declare module "@intric/icons" {
  import { Icon as IconComponent } from "@intric/icons/*";
  export type Icon = typeof IconComponent;
}
declare module "@intric/icons/CPU" {
  export { Icon as IconCPU } from "@intric/icons/*";
}
declare module "@intric/icons/app" {
  export { Icon as IconApp } from "@intric/icons/*";
}
declare module "@intric/icons/arrow-down-to-line" {
  export { Icon as IconArrowDownToLine } from "@intric/icons/*";
}
declare module "@intric/icons/arrow-up-to-line" {
  export { Icon as IconArrowUpToLine } from "@intric/icons/*";
}
declare module "@intric/icons/assistant" {
  export { Icon as IconAssistant } from "@intric/icons/*";
}
declare module "@intric/icons/assistants" {
  export { Icon as IconAssistants } from "@intric/icons/*";
}
declare module "@intric/icons/attachment" {
  export { Icon as IconAttachment } from "@intric/icons/*";
}
declare module "@intric/icons/bulb" {
  export { Icon as IconBulb } from "@intric/icons/*";
}
declare module "@intric/icons/calendar" {
  export { Icon as IconCalendar } from "@intric/icons/*";
}
declare module "@intric/icons/cancel" {
  export { Icon as IconCancel } from "@intric/icons/*";
}
declare module "@intric/icons/check" {
  export { Icon as IconCheck } from "@intric/icons/*";
}
declare module "@intric/icons/chevron-down" {
  export { Icon as IconChevronDown } from "@intric/icons/*";
}
declare module "@intric/icons/chevron-right" {
  export { Icon as IconChevronRight } from "@intric/icons/*";
}
declare module "@intric/icons/chevron-up-down" {
  export { Icon as IconChevronUpDown } from "@intric/icons/*";
}
declare module "@intric/icons/circle" {
  export { Icon as IconCircle } from "@intric/icons/*";
}
declare module "@intric/icons/code" {
  export { Icon as IconCode } from "@intric/icons/*";
}
declare module "@intric/icons/cog" {
  export { Icon as IconCog } from "@intric/icons/*";
}
declare module "@intric/icons/collections" {
  export { Icon as IconCollections } from "@intric/icons/*";
}
declare module "@intric/icons/copy" {
  export { Icon as IconCopy } from "@intric/icons/*";
}
declare module "@intric/icons/document" {
  export { Icon as IconDocument } from "@intric/icons/*";
}
declare module "@intric/icons/download" {
  export { Icon as IconDownload } from "@intric/icons/*";
}
declare module "@intric/icons/drop-file" {
  export { Icon as IconDropFile } from "@intric/icons/*";
}
declare module "@intric/icons/edit" {
  export { Icon as IconEdit } from "@intric/icons/*";
}
declare module "@intric/icons/ellipsis" {
  export { Icon as IconEllipsis } from "@intric/icons/*";
}
declare module "@intric/icons/enter" {
  export { Icon as IconEnter } from "@intric/icons/*";
}
declare module "@intric/icons/feedback" {
  export { Icon as IconFeedback } from "@intric/icons/*";
}
declare module "@intric/icons/file-audio" {
  export { Icon as IconFileAudio } from "@intric/icons/*";
}
declare module "@intric/icons/file-image" {
  export { Icon as IconFileImage } from "@intric/icons/*";
}
declare module "@intric/icons/file-text" {
  export { Icon as IconFileText } from "@intric/icons/*";
}
declare module "@intric/icons/file" {
  export { Icon as IconFile } from "@intric/icons/*";
}
declare module "@intric/icons/filter" {
  export { Icon as IconFilter } from "@intric/icons/*";
}
declare module "@intric/icons/history" {
  export { Icon as IconHistory } from "@intric/icons/*";
}
declare module "@intric/icons/info" {
  export { Icon as IconInfo } from "@intric/icons/*";
}
declare module "@intric/icons/intric" {
  export { Icon as IconIntric } from "@intric/icons/*";
}
declare module "@intric/icons/key" {
  export { Icon as IconKey } from "@intric/icons/*";
}
declare module "@intric/icons/knowledge" {
  export { Icon as IconKnowledge } from "@intric/icons/*";
}
declare module "@intric/icons/library" {
  export { Icon as IconLibrary } from "@intric/icons/*";
}
declare module "@intric/icons/link-external" {
  export { Icon as IconLinkExternal } from "@intric/icons/*";
}
declare module "@intric/icons/link" {
  export { Icon as IconLink } from "@intric/icons/*";
}
declare module "@intric/icons/list-arrows" {
  export { Icon as IconListArrows } from "@intric/icons/*";
}
declare module "@intric/icons/list" {
  export { Icon as IconList } from "@intric/icons/*";
}
declare module "@intric/icons/loading-spinner" {
  export { Icon as IconLoadingSpinner } from "@intric/icons/*";
}
declare module "@intric/icons/logout" {
  export { Icon as IconLogout } from "@intric/icons/*";
}
declare module "@intric/icons/microphone" {
  export { Icon as IconMicrophone } from "@intric/icons/*";
}
declare module "@intric/icons/move" {
  export { Icon as IconMove } from "@intric/icons/*";
}
declare module "@intric/icons/notification-dot" {
  export { Icon as IconNotificationDot } from "@intric/icons/*";
}
declare module "@intric/icons/notification" {
  export { Icon as IconNotification } from "@intric/icons/*";
}
declare module "@intric/icons/overview" {
  export { Icon as IconOverview } from "@intric/icons/*";
}
declare module "@intric/icons/play" {
  export { Icon as IconPlay } from "@intric/icons/*";
}
declare module "@intric/icons/plus" {
  export { Icon as IconPlus } from "@intric/icons/*";
}
declare module "@intric/icons/print" {
  export { Icon as IconPrint } from "@intric/icons/*";
}
declare module "@intric/icons/profile" {
  export { Icon as IconProfile } from "@intric/icons/*";
}
declare module "@intric/icons/question-mark" {
  export { Icon as IconQuestionMark } from "@intric/icons/*";
}
declare module "@intric/icons/refresh" {
  export { Icon as IconRefresh } from "@intric/icons/*";
}
declare module "@intric/icons/search" {
  export { Icon as IconSearch } from "@intric/icons/*";
}
declare module "@intric/icons/selected-item" {
  export { Icon as IconSelectedItem } from "@intric/icons/*";
}
declare module "@intric/icons/service" {
  export { Icon as IconService } from "@intric/icons/*";
}
declare module "@intric/icons/services" {
  export { Icon as IconServices } from "@intric/icons/*";
}
declare module "@intric/icons/session" {
  export { Icon as IconSession } from "@intric/icons/*";
}
declare module "@intric/icons/share" {
  export { Icon as IconShare } from "@intric/icons/*";
}
declare module "@intric/icons/sort-asc-desc" {
  export { Icon as IconSortAscDesc } from "@intric/icons/*";
}
declare module "@intric/icons/sort-asc" {
  export { Icon as IconSortAsc } from "@intric/icons/*";
}
declare module "@intric/icons/sort-desc" {
  export { Icon as IconSortDesc } from "@intric/icons/*";
}
declare module "@intric/icons/speech-bubble" {
  export { Icon as IconSpeechBubble } from "@intric/icons/*";
}
declare module "@intric/icons/square" {
  export { Icon as IconSquare } from "@intric/icons/*";
}
declare module "@intric/icons/squares" {
  export { Icon as IconSquares } from "@intric/icons/*";
}
declare module "@intric/icons/star" {
  export { Icon as IconStar } from "@intric/icons/*";
}
declare module "@intric/icons/stop-circle" {
  export { Icon as IconStopCircle } from "@intric/icons/*";
}
declare module "@intric/icons/stop" {
  export { Icon as IconStop } from "@intric/icons/*";
}
declare module "@intric/icons/storage" {
  export { Icon as IconStorage } from "@intric/icons/*";
}
declare module "@intric/icons/thumb" {
  export { Icon as IconThumb } from "@intric/icons/*";
}
declare module "@intric/icons/trash" {
  export { Icon as IconTrash } from "@intric/icons/*";
}
declare module "@intric/icons/upload-cloud" {
  export { Icon as IconUploadCloud } from "@intric/icons/*";
}
declare module "@intric/icons/upload" {
  export { Icon as IconUpload } from "@intric/icons/*";
}
declare module "@intric/icons/web" {
  export { Icon as IconWeb } from "@intric/icons/*";
}
declare module "@intric/icons/x-mark" {
  export { Icon as IconXMark } from "@intric/icons/*";
}
