"""add tenant display name
Revision ID: 1e4944f4d28c
Revises: 3f7102c90db7
Create Date: 2024-02-26 13:16:33.170350
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '1e4944f4d28c'
down_revision = '3f7102c90db7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'display_name')
    # ### end Alembic commands ###
