"""add org to ai models
Revision ID: 5a012bbe9928
Revises: 30ddedafab78
Create Date: 2024-07-04 12:37:14.614965
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "5a012bbe9928"
down_revision = "30ddedafab78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("completion_models", sa.Column("org", sa.String(), nullable=True))
    op.add_column("embedding_models", sa.Column("org", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("embedding_models", "org")
    op.drop_column("completion_models", "org")
    # ### end Alembic commands ###
