"""completion models remove enum
Revision ID: d48c7ec8a356
Revises: 39082f9d8db9
Create Date: 2024-05-16 11:09:40.590503
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision = "d48c7ec8a356"
down_revision = "39082f9d8db9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "completion_models",
        "family",
        existing_type=postgresql.ENUM("OPEN_AI", "MISTRAL", "VLLM", name="modelfamily"),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "completion_models",
        "stability",
        existing_type=postgresql.ENUM("STABLE", "EXPERIMENTAL", name="modelstability"),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "completion_models",
        "hosting",
        existing_type=postgresql.ENUM("USA", "EU", name="modelhostinglocation"),
        type_=sa.String(),
        existing_nullable=False,
    )

    postgresql.ENUM("OPEN_AI", "MISTRAL", "VLLM", name="modelfamily").drop(
        op.get_bind(), checkfirst=True
    )
    postgresql.ENUM("STABLE", "EXPERIMENTAL", name="modelstability").drop(
        op.get_bind(), checkfirst=True
    )
    postgresql.ENUM("USA", "EU", name="modelhostinglocation").drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    modelfamily_enum = postgresql.ENUM(
        "OPEN_AI", "MISTRAL", "VLLM", name="modelfamily"
    ).create(op.get_bind(), checkfirst=True)
    modelstability_enum = postgresql.ENUM(
        "STABLE", "EXPERIMENTAL", name="modelstability"
    ).create(op.get_bind(), checkfirst=True)
    modelhostinglocation_enum = postgresql.ENUM(
        "USA", "EU", name="modelhostinglocation"
    ).create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "completion_models",
        "hosting",
        existing_type=sa.String(),
        type_=modelhostinglocation_enum,
        existing_nullable=False,
    )
    op.alter_column(
        "completion_models",
        "stability",
        existing_type=sa.String(),
        type_=modelstability_enum,
        existing_nullable=False,
    )
    op.alter_column(
        "completion_models",
        "family",
        existing_type=sa.String(),
        type_=modelfamily_enum,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
