"""user groups to assistants services groups
Revision ID: da01f46a7996
Revises: 87bfca1ad91f
Create Date: 2024-04-03 12:05:06.674356
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "da01f46a7996"
down_revision = "87bfca1ad91f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usergroups_assistants",
        sa.Column("assistants_id", sa.Integer(), nullable=False),
        sa.Column("user_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assistants_id"], ["assistants.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_group_id"], ["user_groups.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("assistants_id", "user_group_id"),
    )
    op.create_table(
        "usergroups_groups",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("user_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_group_id"], ["user_groups.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("group_id", "user_group_id"),
    )
    op.create_table(
        "usergroups_services",
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("user_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["service_id"], ["assistants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_group_id"], ["user_groups.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("service_id", "user_group_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usergroups_services")
    op.drop_table("usergroups_groups")
    op.drop_table("usergroups_assistants")
    # ### end Alembic commands ###
