"""add tenant
Revision ID: 2b9ef0edd2fc
Revises: e7e8c83d7eff
Create Date: 2023-10-05 09:24:50.783525
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '2b9ef0edd2fc'
down_revision = 'e7e8c83d7eff'
branch_labels = None
depends_on = None

GET_EMAIL = """
    SELECT email
    FROM users
"""

INSERT_TENANT = """
    UPDATE users
    SET tenant = (%s)
    WHERE email = %s
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tenant', sa.Text()))
    op.drop_column('info_blobs', 'source')

    # Get all emails
    conn = op.get_bind()
    res = conn.execute(sa.text(GET_EMAIL))
    results = res.fetchall()

    # Insert tenant into database
    for res in results:
        email = res[0]
        tenant_name = email.split('@')[-1].split('.')[0]

        conn.execute(sa.text(INSERT_TENANT), tenant_name, email)

    op.alter_column('users', 'tenant', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tenant')
    op.add_column('info_blobs', sa.Column('source', sa.Text()))
    # ### end Alembic commands ###
