"""cleanup after info-blobs
Revision ID: fa23d657b13e
Revises: a6b31554ab18
Create Date: 2024-07-01 11:21:30.394789
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'fa23d657b13e'
down_revision = 'a6b31554ab18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'info_blob_references', 'info_blob_id', existing_type=sa.UUID(), nullable=False
    )
    op.drop_index(
        'ix_info_blob_references_question_id', table_name='info_blob_references'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_info_blob_references_question_id',
        'info_blob_references',
        ['question_id'],
        unique=False,
    )
    op.alter_column(
        'info_blob_references', 'info_blob_id', existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
