"""add created_at and updated_at to assistants_groups and assistants_webites
Revision ID: 43463e0c7d4a
Revises: 5413e11274c4
Create Date: 2024-07-31 16:59:52.848297
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '43463e0c7d4a'
down_revision = '5413e11274c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'assistants_groups',
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
    )
    op.add_column(
        'assistants_groups',
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
    )
    op.add_column(
        'assistants_websites',
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
    )
    op.add_column(
        'assistants_websites',
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants_websites', 'updated_at')
    op.drop_column('assistants_websites', 'created_at')
    op.drop_column('assistants_groups', 'updated_at')
    op.drop_column('assistants_groups', 'created_at')
    # ### end Alembic commands ###
