"""add api_key to users indexed
Revision ID: 2cfd433ebbed
Revises: f86bab2a902c
Create Date: 2023-09-16 16:09:17.004942
"""

import secrets

import sqlalchemy as sa

from alembic import op
from intric.main.config import get_settings

API_KEY_COLUMN_NAME = "api_key"
USERS_TABLE_NAME = "users"


INSERT_API_KEY_INTO_USERS = """
    UPDATE users
    SET api_key = (%s)
    WHERE id = %s
"""

GET_ALL_USERS_AND_API_KEY = """
    SELECT id, api_key
    from users
"""


# revision identifiers, used by Alembic
revision = '2cfd433ebbed'
down_revision = 'f86bab2a902c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=False)
    # ### end Alembic commands ###

    conn = op.get_bind()
    res = conn.execute(sa.text(GET_ALL_USERS_AND_API_KEY))
    all_users = res.fetchall()

    users_without_api_key = [user for user in all_users if user[1] is None]

    for user in users_without_api_key:
        new_api_key = secrets.token_urlsafe(get_settings().api_key_length)
        conn.execute(sa.text(INSERT_API_KEY_INTO_USERS), new_api_key, user[0])

    op.alter_column('users', "api_key", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###
