"""rename column image to blob
Revision ID: d597b119fc2f
Revises: a6bfd4d8cda8
Create Date: 2024-10-21 10:31:28.616976
"""

from alembic import op

# revision identifiers, used by Alembic
revision = 'd597b119fc2f'
down_revision = 'a6bfd4d8cda8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'image', new_column_name='blob')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'blob', new_column_name='image')
    # ### end Alembic commands ###
