"""add index to email field
Revision ID: 9f3a54ea0ea6
Revises: 73f42a3b4915
Create Date: 2024-11-22 12:17:44.185401
"""

from alembic import op

# revision identifiers, used by Alembic
revision = '9f3a54ea0ea6'
down_revision = '73f42a3b4915'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###
