"""add assistants_files
Revision ID: 73f42a3b4915
Revises: 1849acd7ad19
Create Date: 2024-10-30 08:47:30.470090
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '73f42a3b4915'
down_revision = '1849acd7ad19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'assistants_files',
        sa.Column('assistant_id', sa.UUID(), nullable=False),
        sa.Column('file_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['assistant_id'], ['assistants.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('assistant_id', 'file_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistants_files')
    # ### end Alembic commands ###
