"""service_id on questions
Revision ID: a5f62e624681
Revises: ffedac495127
Create Date: 2023-12-30 15:11:57.065665
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'a5f62e624681'
down_revision = 'ffedac495127'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_index(
        op.f('ix_questions_service_id'), 'questions', ['service_id'], unique=False
    )
    op.create_foreign_key(
        'questions_services_fk',
        'questions',
        'assistants',
        ['service_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_services_fk', 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_service_id'), table_name='questions')
    op.drop_column('questions', 'service_id')
    # ### end Alembic commands ###
