"""groups space_id
Revision ID: 26b6ab68a5a9
Revises: dc0bdb7c04d6
Create Date: 2024-07-16 10:54:24.066449
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "26b6ab68a5a9"
down_revision = "dc0bdb7c04d6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("space_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "groups", "spaces", ["space_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "groups", type_="foreignkey")
    op.drop_column("groups", "space_id")
    # ### end Alembic commands ###
