"""servicesgroups table update
Revision ID: ec23b59d7df1
Revises: 9b3552df4360
Create Date: 2024-08-14 12:22:04.767558
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "ec23b59d7df1"
down_revision = "9b3552df4360"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services_groups",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "services_groups",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("services_groups", "updated_at")
    op.drop_column("services_groups", "created_at")
    # ### end Alembic commands ###
