"""add allowed origins table and privacy policy column
Revision ID: 4b0ed4e04181
Revises: 3d889cf8c102
Create Date: 2024-04-05 11:28:23.565142
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '4b0ed4e04181'
down_revision = '3d889cf8c102'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'allowed_origins',
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'uuid',
            sa.UUID(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_allowed_origins_id'), 'allowed_origins', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_allowed_origins_url'), 'allowed_origins', ['url'], unique=True
    )
    op.create_index(
        op.f('ix_allowed_origins_uuid'), 'allowed_origins', ['uuid'], unique=True
    )
    op.add_column('tenants', sa.Column('privacy_policy', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'privacy_policy')
    op.drop_index(op.f('ix_allowed_origins_uuid'), table_name='allowed_origins')
    op.drop_index(op.f('ix_allowed_origins_url'), table_name='allowed_origins')
    op.drop_index(op.f('ix_allowed_origins_id'), table_name='allowed_origins')
    op.drop_table('allowed_origins')
    # ### end Alembic commands ###
