"""remove widget api keys
Revision ID: 3d889cf8c102
Revises: 87bfca1ad91f
Create Date: 2024-04-04 21:19:06.335136
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '3d889cf8c102'
down_revision = '87bfca1ad91f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('api_keys_widget_unique', 'api_keys', type_='unique')
    op.drop_constraint('api_keys_widgets_fk', 'api_keys', type_='foreignkey')
    op.drop_column('api_keys', 'widget_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'api_keys',
        sa.Column('widget_id', sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        'api_keys_widgets_fk',
        'api_keys',
        'widgets',
        ['widget_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_unique_constraint('api_keys_widget_unique', 'api_keys', ['widget_id'])
    # ### end Alembic commands ###
