"""add json_schema
Revision ID: 1b00efd60345
Revises: 024d9a6c22af
Create Date: 2023-11-20 16:21:12.283466
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision = '1b00efd60345'
down_revision = '024d9a6c22af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'assistants',
        sa.Column(
            'json_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'json_schema')
    # ### end Alembic commands ###
