"""chatbot_widget simple jsonb no default
Revision ID: e7e8c83d7eff
Revises: 2cfd433ebbed
Create Date: 2023-09-23 12:40:37.592185
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision = 'e7e8c83d7eff'
down_revision = '2cfd433ebbed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'settings',
        sa.Column(
            'chatbot_widget', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'chatbot_widget')
    # ### end Alembic commands ###
