"""users deleted_at
Revision ID: 1075a164c954
Revises: 18eea234eb76
Create Date: 2024-03-25 14:21:10.576093
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "1075a164c954"
down_revision = "18eea234eb76"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "deleted_at")
    # ### end Alembic commands ###
