"""set group_id non-nullable
Revision ID: 06db4f2e8a23
Revises: 68dd00d75f21
Create Date: 2023-12-26 10:44:46.119240
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '06db4f2e8a23'
down_revision = '68dd00d75f21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM info_blobs WHERE group_id IS NULL"))
    op.alter_column(
        'info_blobs',
        'id',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        'info_blobs',
        'text',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column('info_blobs', 'user_id', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        'info_blobs',
        'title',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        'info_blobs',
        'url',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        'info_blobs', 'group_id', existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        'info_blobs',
        'embedding_model',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'info_blobs',
        'embedding_model',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.alter_column('info_blobs', 'group_id', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        'info_blobs',
        'url',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        'info_blobs',
        'title',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column('info_blobs', 'user_id', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        'info_blobs',
        'text',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        'info_blobs',
        'id',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
