"""add similarity to info_blobs_references
Revision ID: e0fe14982bcf
Revises: a5f62e624681
Create Date: 2024-01-08 10:44:18.709511
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'e0fe14982bcf'
down_revision = 'a5f62e624681'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'info_blob_references', sa.Column('similarity_score', sa.Float(), nullable=True)
    )
    op.alter_column(
        'info_blob_references',
        'info_blob_id',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_index('ix_info_blob_references_id', table_name='info_blob_references')
    op.create_index(
        op.f('ix_info_blob_references_info_blob_id'),
        'info_blob_references',
        ['info_blob_id'],
        unique=False,
    )
    op.drop_column('settings', 'chat_model_prompt')
    op.drop_column('settings', 'embedding_model')
    op.drop_column('settings', 'chat_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'settings',
        sa.Column('chat_model', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'settings',
        sa.Column('embedding_model', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'settings',
        sa.Column('chat_model_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_index(
        op.f('ix_info_blob_references_info_blob_id'), table_name='info_blob_references'
    )
    op.create_index(
        'ix_info_blob_references_id', 'info_blob_references', ['id'], unique=False
    )
    op.alter_column(
        'info_blob_references',
        'info_blob_id',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column('info_blob_references', 'similarity_score')
    # ### end Alembic commands ###
