"""spaces tenant
Revision ID: 93fd5fb323db
Revises: d41caeadf1be
Create Date: 2024-07-08 13:44:37.955514
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "93fd5fb323db"
down_revision = "d41caeadf1be"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("spaces", sa.Column("tenant_id", sa.UUID(), nullable=False))
    op.drop_constraint("spaces_users_fkey", "spaces", type_="foreignkey")
    op.create_foreign_key(
        None, "spaces", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("spaces", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spaces", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "spaces", type_="foreignkey")
    op.create_foreign_key(
        "spaces_users_fkey", "spaces", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("spaces", "tenant_id")
    # ### end Alembic commands ###
