"""completion models settings
Revision ID: 663040a05fcb
Revises: 116db4f9d44e
Create Date: 2024-06-10 11:59:13.025822
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "663040a05fcb"
down_revision = "116db4f9d44e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "completion_model_settings",
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("completion_model_id", sa.UUID(), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="False", nullable=False),
        sa.Column(
            "is_org_enabled", sa.Boolean(), server_default="False", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["completion_model_id"], ["completion_models.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "completion_model_id"),
    )
    op.create_index(
        "completion_model_is_default_unique",
        "completion_model_settings",
        ["is_default", "tenant_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.drop_table("usergroups_completion_models")
    op.add_column(
        "completion_models",
        sa.Column(
            "is_deprecated", sa.Boolean(), server_default="False", nullable=False
        ),
    )
    op.drop_column("completion_models", "selectable")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "completion_models",
        sa.Column("selectable", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("completion_models", "is_deprecated")
    op.create_table(
        "usergroups_completion_models",
        sa.Column(
            "completion_model_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("user_group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["completion_model_id"],
            ["completion_models.id"],
            name="usergroups_completion_models_completion_model_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_group_id"],
            ["user_groups.id"],
            name="usergroups_completion_models_user_group_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "completion_model_id",
            "user_group_id",
            name="usergroups_completion_models_pkey",
        ),
    )
    op.drop_index(
        "completion_model_is_default_unique",
        table_name="completion_model_settings",
        postgresql_where=sa.text("is_default"),
    )
    op.drop_table("completion_model_settings")
    # ### end Alembic commands ###
