"""created_with on users
Revision ID: ffedac495127
Revises: 06db4f2e8a23
Create Date: 2023-12-26 15:13:46.785299
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'ffedac495127'
down_revision = '06db4f2e8a23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_with', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_with')
    # ### end Alembic commands ###
