"""add logging details to question
Revision ID: 9271779d8dc3
Revises: 6f7e4a4ecae3
Create Date: 2023-12-17 13:15:54.799270
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '9271779d8dc3'
down_revision = '6f7e4a4ecae3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("modules_unique", 'modules', ['name'])
    op.add_column(
        'questions', sa.Column('logging_details_id', sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "questions_logging_fkey",
        'questions',
        'logging',
        ['logging_details_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.alter_column(
        'users',
        'username',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        'users',
        'email',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        'users',
        'salt',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        'users',
        'password',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        'users',
        'api_key',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'api_key',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        'users',
        'password',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        'users',
        'salt',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        'users',
        'email',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        'users',
        'username',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_constraint("questions_logging_fkey", 'questions', type_='foreignkey')
    op.drop_column('questions', 'logging_details_id')
    op.drop_constraint("modules_unique", 'modules', type_='unique')
    # ### end Alembic commands ###
