"""add crawl type
Revision ID: c843a5d42a54
Revises: e3c6ceadc18f
Create Date: 2024-05-10 13:29:16.606143
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'c843a5d42a54'
down_revision = 'e3c6ceadc18f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    sa.Enum('CRAWL', 'SITEMAP', name='crawltype').create(conn, checkfirst=True)

    op.add_column(
        'crawls',
        sa.Column(
            'crawl_type', sa.Enum('CRAWL', 'SITEMAP', name='crawltype'), nullable=True
        ),
    )

    conn.execute(sa.text("UPDATE crawls SET crawl_type='CRAWL'"))

    op.alter_column('crawls', "crawl_type", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawls', 'crawl_type')
    sa.Enum('CRAWL', 'SITEMAP', name='crawltype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
