"""update sessions table
Revision ID: c3f12b97052d
Revises: 2f93af2d8d5c
Create Date: 2023-08-10 10:39:18.664215
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic
revision = 'c3f12b97052d'
down_revision = '2f93af2d8d5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_groups_created_at', table_name='groups')
    op.drop_index('ix_groups_updated_at', table_name='groups')
    op.alter_column('info_blobs', 'text', existing_type=sa.TEXT(), nullable=False)
    op.drop_constraint('info_blobs_path_key', 'info_blobs', type_='unique')
    op.drop_index('ix_info_blobs_created_at', table_name='info_blobs')
    op.drop_index('ix_info_blobs_updated_at', table_name='info_blobs')
    op.create_index(
        op.f('ix_info_blobs_user_id'), 'info_blobs', ['user_id'], unique=False
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.drop_index('ix_settings_created_at', table_name='settings')
    op.drop_index('ix_settings_updated_at', table_name='settings')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_updated_at', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_username_key", 'users', type_='unique')
    op.drop_constraint("users_email_key", 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_updated_at', 'users', ['updated_at'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_settings_updated_at', 'settings', ['updated_at'], unique=False)
    op.create_index('ix_settings_created_at', 'settings', ['created_at'], unique=False)
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_info_blobs_user_id'), table_name='info_blobs')
    op.create_index(
        'ix_info_blobs_updated_at', 'info_blobs', ['updated_at'], unique=False
    )
    op.create_index(
        'ix_info_blobs_created_at', 'info_blobs', ['created_at'], unique=False
    )
    op.create_unique_constraint('info_blobs_path_key', 'info_blobs', ['path'])
    op.alter_column('info_blobs', 'text', existing_type=sa.TEXT(), nullable=True)
    op.create_index('ix_groups_updated_at', 'groups', ['updated_at'], unique=False)
    op.create_index('ix_groups_created_at', 'groups', ['created_at'], unique=False)
    # ### end Alembic commands ###
