"""files image field
Revision ID: b8e460a7894f
Revises: 0ba68e5351dc
Create Date: 2024-07-25 15:10:26.430354
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision = "b8e460a7894f"
down_revision = "0ba68e5351dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("image", postgresql.BYTEA(), nullable=True))
    op.add_column(
        "files",
        sa.Column("file_type", sa.String(), server_default="text", nullable=False),
    )
    op.alter_column("files", "text", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "text", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("files", "file_type")
    op.drop_column("files", "image")
    # ### end Alembic commands ###
