"""remove services_usergroups table
Revision ID: 9d65b11e8913
Revises: c20d7af5d8b6
Create Date: 2024-08-06 12:12:41.694805
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "9d65b11e8913"
down_revision = "c20d7af5d8b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usergroups_services")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usergroups_services",
        sa.Column("service_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_group_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name="usergroups_services_services_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_group_id"],
            ["user_groups.id"],
            name="usergroups_services_user_groups_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_group_id", "service_id", name="usergroups_services_pkey"
        ),
    )
    # ### end Alembic commands ###
