"""files mimetype field
Revision ID: f15e4e8d01a4
Revises: 5413e11274c4
Create Date: 2024-07-31 14:59:43.950641
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "f15e4e8d01a4"
down_revision = "5413e11274c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("mimetype", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "mimetype")
    # ### end Alembic commands ###
