"""change file_questions to questions_files
Revision ID: 116db4f9d44e
Revises: be514f00fd6b
Create Date: 2024-06-05 14:32:25.601706
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision = '116db4f9d44e'
down_revision = 'be514f00fd6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'questions_files',
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('file_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('question_id', 'file_id'),
    )
    op.drop_table('files_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'files_questions',
        sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['file_id'],
            ['files.id'],
            name='files_questions_file_id_fkey',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['question_id'],
            ['questions.id'],
            name='files_questions_question_id_fkey',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('file_id', 'question_id', name='files_questions_pkey'),
    )
    op.drop_table('questions_files')
    # ### end Alembic commands ###
