"""remove groups_usergroups table
Revision ID: b383fccf1684
Revises: 9d65b11e8913
Create Date: 2024-08-06 13:15:15.086164
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "b383fccf1684"
down_revision = "9d65b11e8913"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usergroups_groups")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usergroups_groups",
        sa.Column("group_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_group_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name="usergroups_groups_groups_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_group_id"],
            ["user_groups.id"],
            name="usergroups_groups_user_groups_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_group_id", "group_id", name="usergroups_groups_pkey"
        ),
    )
    # ### end Alembic commands ###
