"""add uuid to questions
Revision ID: 024d9a6c22af
Revises: bd98d305fb94
Create Date: 2023-11-16 09:51:04.355651
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision = '024d9a6c22af'
down_revision = 'bd98d305fb94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assistants_uuid', table_name='assistants')
    op.create_index(op.f('ix_assistants_uuid'), 'assistants', ['uuid'], unique=True)
    op.add_column(
        'questions',
        sa.Column(
            'uuid',
            postgresql.UUID(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
    )
    op.create_index(op.f('ix_questions_uuid'), 'questions', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_uuid'), table_name='questions')
    op.drop_column('questions', 'uuid')
    op.drop_index(op.f('ix_assistants_uuid'), table_name='assistants')
    op.create_index('ix_assistants_uuid', 'assistants', ['uuid'], unique=False)
    # ### end Alembic commands ###
