"""services table space_id field
Revision ID: 9b3552df4360
Revises: b383fccf1684
Create Date: 2024-08-13 13:57:27.530069
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "9b3552df4360"
down_revision = "b383fccf1684"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("services", sa.Column("space_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "services", "spaces", ["space_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "services", type_="foreignkey")
    op.drop_column("services", "space_id")
    # ### end Alembic commands ###
