"""remove assistants_usergroups table
Revision ID: c20d7af5d8b6
Revises: 4978d82608b6
Create Date: 2024-08-06 10:24:18.971488
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "c20d7af5d8b6"
down_revision = "4978d82608b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usergroups_assistants")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usergroups_assistants",
        sa.Column("assistant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_group_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            name="usergroups_assistants_assistants_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_group_id"],
            ["user_groups.id"],
            name="usergroups_assistants_user_groups_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_group_id", "assistant_id", name="usergroups_assistants_pkey"
        ),
    )
    # ### end Alembic commands ###
