"""added domain and zitadel org id
Revision ID: bd5e20893670
Revises: ab047a3c6ea9
Create Date: 2024-08-27 16:37:20.371816
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'bd5e20893670'
down_revision = 'ab047a3c6ea9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('zitadel_org_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'zitadel_org_id')
    op.drop_column('tenants', 'domain')
    # ### end Alembic commands ###
