"""add cascade to steps.service_id, add unique to user.email, remove alphanumeric
Revision ID: dc0bdb7c04d6
Revises: 2b88a8ef82ac
Create Date: 2024-07-15 20:00:06.957590
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'dc0bdb7c04d6'
down_revision = '2b88a8ef82ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('steps_service_id_fkey', 'steps', type_='foreignkey')
    op.create_foreign_key(
        None, 'steps', 'services', ['service_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_constraint('tenants_alphanumeric_unique', 'tenants', type_='unique')
    op.drop_column('tenants', 'alphanumeric')
    op.drop_constraint('users_email_tenant_unique', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(
        'users_email_tenant_unique', 'users', ['email', 'tenant_id']
    )
    op.add_column(
        'tenants',
        sa.Column('alphanumeric', sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        'tenants_alphanumeric_unique', 'tenants', ['alphanumeric']
    )
    op.drop_constraint(None, 'steps', type_='foreignkey')
    op.create_foreign_key(
        'steps_service_id_fkey', 'steps', 'services', ['service_id'], ['id']
    )
    # ### end Alembic commands ###
