"""public assistants
Revision ID: cf75cc6897ab
Revises: 70df51a7b05c
Create Date: 2024-01-25 16:14:18.751097
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'cf75cc6897ab'
down_revision = '70df51a7b05c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('is_public', sa.Boolean(), nullable=True))
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE assistants SET is_public = false"))
    op.alter_column('assistants', 'is_public', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistants', 'is_public')
    # ### end Alembic commands ###
