"""assistants space_id
Revision ID: cd4c329d3b75
Revises: 7e6bd8dcb7cd
Create Date: 2024-07-10 13:22:56.253157
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "cd4c329d3b75"
down_revision = "7e6bd8dcb7cd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistants", sa.Column("space_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "assistants", "spaces", ["space_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "assistants", type_="foreignkey")
    op.drop_column("assistants", "space_id")
    # ### end Alembic commands ###
