"""completion models vision field
Revision ID: 4978d82608b6
Revises: dee77adfe014
Create Date: 2024-08-01 12:07:54.298057
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "4978d82608b6"
down_revision = "dee77adfe014"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "completion_models",
        sa.Column("vision", sa.Boolean(), server_default="False", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("completion_models", "vision")
    # ### end Alembic commands ###
