"""set null ondelete for group in assistants
Revision ID: 3956e5dc413f
Revises: 42d119d21586
Create Date: 2023-11-28 19:20:19.943986
"""

from alembic import op

# revision identifiers, used by Alembic
revision = '3956e5dc413f'
down_revision = '42d119d21586'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assistants_group_id_fkey', 'assistants', type_='foreignkey')
    op.create_foreign_key(
        'assistants_group_id_fkey',
        'assistants',
        'groups',
        ['group_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.drop_constraint('info_blobs_group_id_fkey', 'info_blobs', type_='foreignkey')
    op.create_foreign_key(
        'info_blobs_group_id_fkey', 'info_blobs', 'groups', ['group_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('info_blobs_group_id_fkey', 'info_blobs', type_='foreignkey')
    op.create_foreign_key(
        'info_blobs_group_id_fkey',
        'info_blobs',
        'groups',
        ['group_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.drop_constraint('assistants_group_id_fkey', 'assistants', type_='foreignkey')
    op.create_foreign_key(
        'assistants_group_id_fkey', 'assistants', 'groups', ['group_id'], ['id']
    )
    # ### end Alembic commands ###
