"""declarative tables
Revision ID: e4857d967e73
Revises: c3f12b97052d
Create Date: 2023-08-13 15:58:04.458059
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'e4857d967e73'
down_revision = 'c3f12b97052d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_beta_keys_id'), 'beta_keys', ['id'], unique=False)
    op.alter_column(
        'info_blob_references',
        'question_id',
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.create_index(
        op.f('ix_info_blob_references_id'), 'info_blob_references', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_info_blob_references_question_id'),
        'info_blob_references',
        ['question_id'],
        unique=False,
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(
        op.f('ix_questions_session_id'), 'questions', ['session_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_session_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(
        op.f('ix_info_blob_references_question_id'), table_name='info_blob_references'
    )
    op.drop_index(op.f('ix_info_blob_references_id'), table_name='info_blob_references')
    op.alter_column(
        'info_blob_references', 'question_id', existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_index(op.f('ix_beta_keys_id'), table_name='beta_keys')
    # ### end Alembic commands ###
