"""set embedding model as required
Revision ID: e40d5e614716
Revises: ec23b59d7df1
Create Date: 2024-08-15 16:58:56.480334
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'e40d5e614716'
down_revision = 'ec23b59d7df1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'websites', 'embedding_model_id', existing_type=sa.UUID(), nullable=False
    )
    op.drop_constraint(
        'websites_embedding_model_id_fkey', 'websites', type_='foreignkey'
    )
    op.create_foreign_key(
        'websites_embedding_model_id_fkey',
        'websites',
        'embedding_models',
        ['embedding_model_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'websites_embedding_model_id_fkey', 'websites', type_='foreignkey'
    )
    op.create_foreign_key(
        'websites_embedding_model_id_fkey',
        'websites',
        'embedding_models',
        ['embedding_model_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.alter_column(
        'websites', 'embedding_model_id', existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
