"""chunks
Revision ID: e3c6ceadc18f
Revises: a05ebf86dfed
Create Date: 2024-05-06 08:32:54.870877
"""

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'e3c6ceadc18f'
down_revision = 'a05ebf86dfed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    conn = op.get_bind()
    conn.execute(sa.text('CREATE EXTENSION IF NOT EXISTS vector'))

    op.add_column(
        'info_blobs',
        sa.Column(
            'uuid',
            sa.Uuid(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
    )
    op.create_index(op.f('ix_info_blobs_uuid'), 'info_blobs', ['uuid'], unique=True)

    op.create_table(
        'info_blob_chunks',
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('chunk_no', sa.Integer(), nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.Vector(), nullable=False),
        sa.Column('info_blob_id', sa.Uuid(), nullable=False),
        sa.Column('info_blob_old_id', sa.String(), nullable=False),
        sa.Column(
            'id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False
        ),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['info_blob_id'], ['info_blobs.uuid'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_blob_chunks')
    op.drop_index(op.f('ix_info_blobs_uuid'), table_name='info_blobs')
    op.drop_column('info_blobs', 'uuid')
    # ### end Alembic commands ###
