"""change name of output_validation
Revision ID: 42d119d21586
Revises: 9ababe869e85
Create Date: 2023-11-24 16:09:02.734643
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '42d119d21586'
down_revision = '9ababe869e85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('output_format', sa.Text(), nullable=True))
    op.drop_column('assistants', 'output_validation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'assistants',
        sa.Column('output_validation', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column('assistants', 'output_format')
    # ### end Alembic commands ###
