"""atomic_roles to permissions
Revision ID: 8043137f2894
Revises: cc37bde1572e
Create Date: 2024-04-19 11:00:46.180935
"""

from alembic import op

# revision identifiers, used by Alembic
revision = "8043137f2894"
down_revision = "cc37bde1572e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("roles", "atomic_roles", new_column_name="permissions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("roles", "permissions", new_column_name="atomic_roles")
    # ### end Alembic commands ###
