"""add service_id to sessions
Revision ID: 9ababe869e85
Revises: 1b00efd60345
Create Date: 2023-11-21 12:16:03.755474
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '9ababe869e85'
down_revision = '1b00efd60345'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        "sessions_service_fkey",
        'sessions',
        'assistants',
        ['service_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("sessions_service_fkey", 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'service_id')
    # ### end Alembic commands ###
