"""remove unique usernames
Revision ID: 00ada6bdd27a
Revises: bd5e20893670
Create Date: 2024-09-11 13:36:03.486145
"""

from alembic import op

# revision identifiers, used by Alembic
revision = '00ada6bdd27a'
down_revision = 'bd5e20893670'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_username_tenant_unique', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'users_username_tenant_unique', 'users', ['username', 'tenant_id']
    )
    # ### end Alembic commands ###
