"""add update interval
Revision ID: d2a94cd6034f
Revises: 90f16d7546ae
Create Date: 2024-06-24 08:13:12.785354
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'd2a94cd6034f'
down_revision = '90f16d7546ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('update_interval', sa.String(), nullable=True))

    op.execute(sa.text("UPDATE websites SET update_interval = 'never'"))

    op.alter_column('websites', 'update_interval', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'update_interval')
    # ### end Alembic commands ###
