"""set group to null if group is deleted
Revision ID: cf413adcf3c1
Revises: 7480251bb46b
Create Date: 2024-05-18 18:16:21.027484
"""

from alembic import op

# revision identifiers, used by Alembic
revision = 'cf413adcf3c1'
down_revision = '7480251bb46b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('crawl_runs_job_id_fkey', 'crawl_runs', type_='foreignkey')
    op.drop_constraint('crawl_runs_crawl_id_fkey', 'crawl_runs', type_='foreignkey')
    op.create_foreign_key(
        'crawl_runs_crawl_id_fkey',
        'crawl_runs',
        'crawls',
        ['crawl_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        'crawl_runs_job_id_fkey',
        'crawl_runs',
        'jobs',
        ['job_id'],
        ['uuid'],
        ondelete='SET NULL',
    )
    op.drop_constraint('crawls_groups_fkey', 'crawls', type_='foreignkey')
    op.create_foreign_key(
        'crawls_groups_fkey',
        'crawls',
        'groups',
        ['group_id'],
        ['uuid'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('crawls_groups_fkey', 'crawls', type_='foreignkey')
    op.create_foreign_key(
        'crawls_groups_fkey',
        'crawls',
        'groups',
        ['group_id'],
        ['uuid'],
        ondelete='CASCADE',
    )
    op.drop_constraint('crawl_runs_crawl_id_fkey', 'crawl_runs', type_='foreignkey')
    op.drop_constraint('crawl_runs_job_id_fkey', 'crawl_runs', type_='foreignkey')
    op.create_foreign_key(
        'crawl_runs_crawl_id_fkey', 'crawl_runs', 'crawls', ['crawl_id'], ['id']
    )
    op.create_foreign_key(
        'crawl_runs_job_id_fkey',
        'crawl_runs',
        'jobs',
        ['job_id'],
        ['uuid'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###
