"""add widgets table
Revision ID: 912fecff999a
Revises: 18eea234eb76
Create Date: 2024-03-23 18:51:20.024406
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '912fecff999a'
down_revision = '18eea234eb76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'widgets',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('bot_introduction', sa.String(), nullable=False),
        sa.Column('color', sa.String(), nullable=False),
        sa.Column('size', sa.String(), nullable=False),
        sa.Column('assistant_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'uuid',
            sa.UUID(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['assistant_id'], ['assistants.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_widgets_id'), 'widgets', ['id'], unique=False)
    op.create_index(op.f('ix_widgets_uuid'), 'widgets', ['uuid'], unique=True)
    op.add_column('api_keys', sa.Column('widget_id', sa.Integer(), nullable=True))
    op.create_unique_constraint("api_keys_widget_unique", 'api_keys', ['widget_id'])
    op.create_foreign_key(
        "api_keys_widgets_fk",
        'api_keys',
        'widgets',
        ['widget_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("api_keys_widgets_fk", 'api_keys', type_='foreignkey')
    op.drop_constraint("api_keys_widget_unique", 'api_keys', type_='unique')
    op.drop_column('api_keys', 'widget_id')
    op.drop_index(op.f('ix_widgets_uuid'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_id'), table_name='widgets')
    op.drop_table('widgets')
    # ### end Alembic commands ###
