"""add index to foreign keys
Revision ID: bfa43d57de38
Revises: 22420aa2e86c
Create Date: 2024-08-19 08:40:37.942264
"""

from alembic import op

# revision identifiers, used by Alembic
revision = 'bfa43d57de38'
down_revision = '22420aa2e86c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_info_blob_chunks_info_blob_id'),
        'info_blob_chunks',
        ['info_blob_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_info_blob_chunks_tenant_id'),
        'info_blob_chunks',
        ['tenant_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_info_blobs_website_id'), 'info_blobs', ['website_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_info_blobs_website_id'), table_name='info_blobs')
    op.drop_index(op.f('ix_info_blob_chunks_tenant_id'), table_name='info_blob_chunks')
    op.drop_index(
        op.f('ix_info_blob_chunks_info_blob_id'), table_name='info_blob_chunks'
    )
    # ### end Alembic commands ###
