"""require completion_model_id
Revision ID: 1849acd7ad19
Revises: f80b11f58be6
Create Date: 2024-10-30 07:58:25.994911
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '1849acd7ad19'
down_revision = 'f80b11f58be6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'assistants', 'completion_model_id', existing_type=sa.UUID(), nullable=False
    )
    op.drop_constraint(
        'assistants_completion_model_id_fkey', 'assistants', type_='foreignkey'
    )
    op.create_foreign_key(
        None, 'assistants', 'completion_models', ['completion_model_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assistants', type_='foreignkey')
    op.create_foreign_key(
        'assistants_completion_model_id_fkey',
        'assistants',
        'completion_models',
        ['completion_model_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.alter_column(
        'assistants', 'completion_model_id', existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
