"""make service_id nullable
Revision ID: b68dffb9168e
Revises: ca3818d474d6
Create Date: 2024-07-08 16:26:30.308731
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'b68dffb9168e'
down_revision = 'ca3818d474d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_questions_service_id'), 'questions', ['service_id'], unique=False
    )
    op.alter_column('steps', 'service_id', existing_type=sa.UUID(), nullable=False)
    op.drop_constraint('steps_services_fkey', 'steps', type_='foreignkey')
    op.create_foreign_key(None, 'steps', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'steps', type_='foreignkey')
    op.create_foreign_key(
        'steps_services_fkey',
        'steps',
        'services',
        ['service_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.alter_column('steps', 'service_id', existing_type=sa.UUID(), nullable=True)
    op.drop_index(op.f('ix_questions_service_id'), table_name='questions')
    # ### end Alembic commands ###
