"""add deployment name
Revision ID: 4d352fa56524
Revises: d2a94cd6034f
Create Date: 2024-07-01 08:25:30.488346
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "4d352fa56524"
down_revision = "d2a94cd6034f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "completion_models", sa.Column("deployment_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("completion_models", "deployment_name")
    # ### end Alembic commands ###
