"""remove index type and is_public
Revision ID: 29dd8db386e1
Revises: f7bddc455b6c
Create Date: 2024-05-23 12:10:25.232072
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '29dd8db386e1'
down_revision = 'f7bddc455b6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'index_type')
    op.drop_column('groups', 'is_public')
    op.alter_column('info_blobs', 'group_id', existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('info_blobs', 'group_id', existing_type=sa.UUID(), nullable=True)
    op.add_column(
        'groups',
        sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'groups',
        sa.Column('index_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
