"""users uuid
Revision ID: cc37bde1572e
Revises: 772b05ce5335
Create Date: 2024-04-10 12:00:12.497015
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "cc37bde1572e"
down_revision = "772b05ce5335"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_users_uuid"), "users", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_uuid"), table_name="users")
    op.drop_column("users", "uuid")
    # ### end Alembic commands ###
