"""relationships in sessions
Revision ID: 7bcc05803774
Revises: 217005c19b2c
Create Date: 2023-12-13 13:56:18.907402
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '7bcc05803774'
down_revision = '217005c19b2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'questions',
        'question',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        'questions',
        'answer',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        'questions',
        'model',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.add_column(
        'sessions',
        sa.Column(
            'uuid',
            sa.UUID(),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
    )
    op.alter_column('sessions', 'user_id', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        'sessions',
        'name',
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.create_index(op.f('ix_sessions_uuid'), 'sessions', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_uuid'), table_name='sessions')
    op.alter_column(
        'sessions',
        'name',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column('sessions', 'user_id', existing_type=sa.INTEGER(), nullable=True)
    op.drop_column('sessions', 'uuid')
    op.alter_column(
        'questions',
        'model',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        'questions',
        'answer',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        'questions',
        'question',
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
