"""remove superuser
Revision ID: 46ba9ff51e34
Revises: cf413adcf3c1
Create Date: 2024-05-20 08:46:21.757703
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision = '46ba9ff51e34'
down_revision = 'cf413adcf3c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'crawl_runs',
        'completed_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column('crawls', 'group_id', existing_type=sa.UUID(), nullable=True)
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'is_superuser',
            sa.BOOLEAN(),
            server_default=sa.text('false'),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column('crawls', 'group_id', existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        'crawl_runs',
        'completed_at',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
