"""websites space_id
Revision ID: 0ba68e5351dc
Revises: 26b6ab68a5a9
Create Date: 2024-07-16 17:19:30.749560
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "0ba68e5351dc"
down_revision = "26b6ab68a5a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("websites", sa.Column("space_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "websites", "spaces", ["space_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "websites", type_="foreignkey")
    op.drop_column("websites", "space_id")
    # ### end Alembic commands ###
