"""add name to jobs
Revision ID: cf08d73a0019
Revises: 9ce1be90c179
Create Date: 2024-03-11 11:15:18.997099
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'cf08d73a0019'
down_revision = '9ce1be90c179'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'name')
    # ### end Alembic commands ###
