"""add finished_at to job
Revision ID: 9751d5565531
Revises: 29dd8db386e1
Create Date: 2024-05-25 10:59:24.395538
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision = '9751d5565531'
down_revision = '29dd8db386e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_runs', 'completed_at')
    op.add_column(
        'jobs', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'finished_at')
    op.add_column(
        'crawl_runs',
        sa.Column(
            'completed_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
