"""remove is_default field
Revision ID: f56172ebc222
Revises: 4a1f5dd302ed
Create Date: 2024-06-11 19:39:01.959717
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "f56172ebc222"
down_revision = "4a1f5dd302ed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "completion_model_is_default_unique",
        table_name="completion_model_settings",
        postgresql_where="is_default",
    )
    op.drop_column("completion_model_settings", "is_default")
    op.drop_index(
        "embedding_model_is_default_unique",
        table_name="embedding_model_settings",
        postgresql_where="is_default",
    )
    op.drop_column("embedding_model_settings", "is_default")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "embedding_model_settings",
        sa.Column(
            "is_default",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        "embedding_model_is_default_unique",
        "embedding_model_settings",
        ["is_default", "tenant_id"],
        unique=True,
        postgresql_where="is_default",
    )
    op.add_column(
        "completion_model_settings",
        sa.Column(
            "is_default",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        "completion_model_is_default_unique",
        "completion_model_settings",
        ["is_default", "tenant_id"],
        unique=True,
        postgresql_where="is_default",
    )
    # ### end Alembic commands ###
