"""cleanup after assistants uuid merge
Revision ID: 3cffa1f9001d
Revises: 2c2c43bb1a97
Create Date: 2024-05-28 15:18:30.389577
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '3cffa1f9001d'
down_revision = '2c2c43bb1a97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "api_keys_assistant_id_unique", 'api_keys', ['assistant_id']
    )
    op.alter_column('widgets', 'assistant_id', existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('widgets', 'assistant_id', existing_type=sa.UUID(), nullable=True)
    op.drop_constraint("api_keys_assistant_id_unique", 'api_keys', type_='unique')
    # ### end Alembic commands ###
