"""usergroups_completion_models table
Revision ID: cbd172f4bbdb
Revises: 4376c7633e19
Create Date: 2024-05-28 18:30:09.776335
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "cbd172f4bbdb"
down_revision = "4376c7633e19"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usergroups_completion_models",
        sa.Column("completion_model_id", sa.UUID(), nullable=False),
        sa.Column("user_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["completion_model_id"], ["completion_models.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_group_id"], ["user_groups.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("completion_model_id", "user_group_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usergroups_completion_models")
    # ### end Alembic commands ###
