"""user groups to users
Revision ID: 87bfca1ad91f
Revises: 6c23a47395e4
Create Date: 2024-03-27 13:40:05.706681
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "87bfca1ad91f"
down_revision = "6c23a47395e4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usergroups_users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_group_id"], ["user_groups.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "user_group_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usergroups_users")
    # ### end Alembic commands ###
