"""drop profiles and beta keys
Revision ID: 7e6bd8dcb7cd
Revises: a4f2b2fa574f
Create Date: 2024-07-09 09:28:11.962698
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision = '7e6bd8dcb7cd'
down_revision = 'a4f2b2fa574f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_beta_keys_id', table_name='beta_keys')
    op.drop_table('beta_keys')
    op.drop_index('ix_profiles_id', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'profiles',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name='profiles_users_fkey', ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name='profiles_pkey'),
    )
    op.create_index('ix_profiles_id', 'profiles', ['id'], unique=False)
    op.create_table(
        'beta_keys',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name='beta_keys_pkey'),
    )
    op.create_index('ix_beta_keys_id', 'beta_keys', ['id'], unique=False)
    # ### end Alembic commands ###
