"""add provisioning column to tenants
Revision ID: f2e971bd6c75
Revises: b05cd0792f0f
Create Date: 2024-11-28 15:31:51.847836
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'f2e971bd6c75'
down_revision = 'b05cd0792f0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tenants',
        sa.Column('provisioning', sa.Boolean(), server_default="False", nullable=False),
    )
    op.create_index(
        op.f('ix_tenants_zitadel_org_id'), 'tenants', ['zitadel_org_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_zitadel_org_id'), table_name='tenants')
    op.drop_column('tenants', 'provisioning')
    # ### end Alembic commands ###
