"""Optional completion model id on template tables
Revision ID: f152079c27aa
Revises: f2e971bd6c75
Create Date: 2024-12-03 12:48:51.726867
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = "f152079c27aa"
down_revision = "f2e971bd6c75"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "app_templates", "completion_model_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "assistant_templates",
        "completion_model_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assistant_templates",
        "completion_model_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        "app_templates", "completion_model_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
