"""add published to groups, websites, and assistants
Revision ID: 80c7388d88d3
Revises: 5bfaaae1eacb
Create Date: 2024-12-16 13:38:13.298664
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '80c7388d88d3'
down_revision = '5bfaaae1eacb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new columns as nullable initially
    op.add_column('assistants', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('groups', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('websites', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('published', sa.Boolean(), nullable=True))

    # Execute SQL statements to set default values to False for existing rows
    op.execute(sa.text("UPDATE assistants SET published=False"))
    op.execute(sa.text("UPDATE groups SET published=False"))
    op.execute(sa.text("UPDATE websites SET published=False"))
    op.execute(sa.text("UPDATE services SET published=False"))

    # Alter columns to make them non-nullable
    op.alter_column('assistants', 'published', nullable=False)
    op.alter_column('groups', 'published', nullable=False)
    op.alter_column('websites', 'published', nullable=False)
    op.alter_column('services', 'published', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'published')
    op.drop_column('groups', 'published')
    op.drop_column('assistants', 'published')
    op.drop_column('services', 'published')
    # ### end Alembic commands ###
