"""add default assistants to spaces
Revision ID: 99304a914f6b
Revises: 160aeec42959
Create Date: 2024-12-09 11:34:29.488684
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '99304a914f6b'
down_revision = '160aeec42959'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('is_default', sa.Boolean(), nullable=True))

    # Set all existing entries to False
    op.execute('UPDATE assistants SET is_default = FALSE')

    # Alter column to be not nullable
    op.alter_column('assistants', 'is_default', nullable=False)

    op.alter_column(
        'assistants', 'completion_model_id', existing_type=sa.UUID(), nullable=True
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'assistants', 'completion_model_id', existing_type=sa.UUID(), nullable=False
    )
    op.drop_column('assistants', 'is_default')
    # ### end Alembic commands ###
