"""add state column to user
Revision ID: 4ff470519fc8
Revises: 873bf8b076cd
Create Date: 2024-12-04 08:21:52.969054
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '4ff470519fc8'
down_revision = '873bf8b076cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'state' column as nullable initially
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))

    # Perform data migration to set state based on is_active status
    op.execute(
        """
        UPDATE users
        SET state = CASE
            WHEN is_active = FALSE THEN 'invited'
            WHEN deleted_at != NULL THEN 'deleted'
            ELSE 'active'
        END
    """
    )

    # Alter column to be non-nullable after data migration
    op.alter_column('users', 'state', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'state')
    # ### end Alembic commands ###
