"""add tool_assistant_id to questions
Revision ID: af49c5d45ce3
Revises: a19994071e35
Create Date: 2024-12-23 12:04:35.715941
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'af49c5d45ce3'
down_revision = 'a19994071e35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('tool_assistant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        None,
        'questions',
        'assistants',
        ['tool_assistant_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'tool_assistant_id')
    # ### end Alembic commands ###
