"""remove published from groups and websites
Revision ID: bd881d34acaa
Revises: 914bc48e6e6c
Create Date: 2025-01-13 14:38:00.079880
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'bd881d34acaa'
down_revision = '914bc48e6e6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'published')
    op.drop_column('websites', 'published')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'websites',
        sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        'groups',
        sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
