"""Adding size to Groups
Revision ID: bafa759fdaf8
Revises: 2387d2b6185f
Create Date: 2025-01-20 16:51:45.061229
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "bafa759fdaf8"
down_revision = "2387d2b6185f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Step 1: Add column as nullable
    op.add_column("groups", sa.Column("size", sa.BigInteger(), nullable=True))

    # Step 2: Update existing rows to have a default value
    op.execute(
        """
        UPDATE groups
        SET size = (
            SELECT COALESCE(SUM(size), 0)
            FROM info_blobs
            WHERE info_blobs.group_id = groups.id
            )
        """
    )

    # Step 3: Alter the column to be NOT NULL
    op.alter_column("groups", "size", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "size")
    # ### end Alembic commands ###
