"""add order to info-blob-references
Revision ID: e748bf9c8b1d
Revises: bd881d34acaa
Create Date: 2025-01-13 13:20:20.380341
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = 'e748bf9c8b1d'
down_revision = 'bd881d34acaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'info_blob_references', sa.Column('order', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_blob_references', 'order')
    # ### end Alembic commands ###
