"""Create organization column
Revision ID: 914bc48e6e6c
Revises: 10f99885ca8e
Create Date: 2025-01-13 12:06:04.715818
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = "914bc48e6e6c"
down_revision = "10f99885ca8e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_templates",
        sa.Column("organization", sa.Text(), server_default="default", nullable=False),
    )
    op.add_column(
        "assistant_templates",
        sa.Column("organization", sa.Text(), server_default="default", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistant_templates", "organization")
    op.drop_column("app_templates", "organization")
    # ### end Alembic commands ###
