"""Remove published from services
Revision ID: 77ec960315a1
Revises: bafa759fdaf8
Create Date: 2025-01-25 13:36:31.728301
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = "77ec960315a1"
down_revision = "bafa759fdaf8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("services", "published")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services",
        sa.Column(
            "published",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            default=False,
        ),
    )
    # ### end Alembic commands ###
