"""add preferred to embedding models and completion models
Revision ID: 9f886203509c
Revises: 886e2a01ee1f
Create Date: 2025-01-28 12:48:31.093617
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision = '9f886203509c'
down_revision = '886e2a01ee1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'completion_model_settings',
        sa.Column(
            'is_org_preferred', sa.Boolean(), server_default='False', nullable=False
        ),
    )
    op.add_column(
        'embedding_model_settings',
        sa.Column(
            'is_org_preferred', sa.Boolean(), server_default='False', nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embedding_model_settings', 'is_org_preferred')
    op.drop_column('completion_model_settings', 'is_org_preferred')
    # ### end Alembic commands ###
