"""Add constraints to feature tabls
Revision ID: 10f99885ca8e
Revises: 10bc15517804
Create Date: 2025-01-08 14:29:42.237086
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = "10f99885ca8e"
down_revision = "10bc15517804"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "global_feature_flags_name_key", "global_feature_flags", ["name"]
    )
    op.alter_column(
        "tenant_feature_flags", "name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("tenant_feature_flags", "id")
    op.create_primary_key(
        "pk_tenant_feature_flags_feature_id_tenant_id",
        "tenant_feature_flags",
        columns=["feature_id", "tenant_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenant_feature_flags",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "tenant_feature_flags", "name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint(
        "global_feature_flags_name_key", "global_feature_flags", type_="unique"
    )
    # ### end Alembic commands ###
