# flake8: noqa

import intric.database.tables.ai_models_table
import intric.database.tables.allowed_origins_table
import intric.database.tables.api_keys_table
import intric.database.tables.app_table
import intric.database.tables.assistant_table
import intric.database.tables.assistant_template_table
import intric.database.tables.files_table
import intric.database.tables.groups_table
import intric.database.tables.info_blob_chunk_table
import intric.database.tables.info_blobs_table
import intric.database.tables.job_table
import intric.database.tables.logging_table
import intric.database.tables.module_table
import intric.database.tables.prompts_table
import intric.database.tables.questions_table
import intric.database.tables.roles_table
import intric.database.tables.service_table
import intric.database.tables.sessions_table
import intric.database.tables.settings_table
import intric.database.tables.spaces_table
import intric.database.tables.tenant_table
import intric.database.tables.user_groups_table
import intric.database.tables.users_table
import intric.database.tables.websites_table
import intric.database.tables.widget_table
import intric.database.tables.workflow_tables
import intric.database.tables.app_template_table
import intric.database.tables.feature_flag_table
import intric.database.tables.integration_table
